version: '3.7'
services:
  jupyterhub:
    build: .
    command:
      - /opt/conda/bin/python3
      - /opt/conda/bin/jupyterhub
      - --debug
    volumes:
    - /var/run/docker.sock:/var/run/docker.sock
    - ./cookies:/srv/jupyterhub/cookies
    - ./db:/srv/jupyterhub/db
    environment:
    - OAUTH_ENDPOINT=https://iam-demo.cloud.cnaf.infn.it
    - OAUTH_CALLBACK_URL=http://<YOUR HOST HERE>:8888/hub/oauth_callback
    - OAUTH_GROUPS=covid_env
    - WITH_GPU=false
  http_proxy:
    image: jupyterhub/configurable-http-proxy
    command:
      - configurable-http-proxy
      - --ip=0.0.0.0
      - --port=8888
      - --api-ip=0.0.0.0
      - --api-port=8001
      - --default-target=http://jupyterhub:8088
      - --error-target=http://jupyterhub:8088/hub/error
    environment:
      - CONFIGPROXY_AUTH_TOKEN=testme
    ports:
      - 8888:8888
      - 8001
networks:
  default:
    name: jupyterhub
